### ISSUE TITLE
Care to free up the "boring" npm namespace? :D

### ISSUE THREAD

**Issue by josheverett** [apostrophecms/boring#1]
Hey there! My partner and I are interested in acquiring the "boring" npm name for a project we are actively developing. Given that this project appears to be dead, would you be open to a discussion about transferring the npm name? Thanks!

**Comment by boutell** [comment]
Hi,

While the module is certainly moribund it is not dead — it's in active use on 12 projects. They are not large projects, but we use them, and that's a lot to change. It hasn't been updated because it is straightforward and no updates are required (that's sort of the point with this module). Best wishes with your project.

**Comment by josheverett** [comment]
Thanks for taking the time to respond to this, much appreciated! We'll soldier on with pseudo @namespaces. ;)
